@RiverBooks_WebAddress = https://localhost:7086

GET {{RiverBooks_WebAddress}}/books/
Accept: application/json

###

@BookID=b89f6cd7-3d3d-4d3d-8d3d-3d3d3d3d3d3d
GET {{RiverBooks_WebAddress}}/books/{{BookID}}
Accept: application/json

###

POST {{RiverBooks_WebAddress}}/books/
Accept: application/json
Content-Type: application/json
{
  "id": "d89f6cd7-3d3d-4d3d-8d3d-3d3d3d3d3d3d",
  "title": "The River",
  "author": "Peter Heller",
  "price": 15.99
}

###
DELETE {{RiverBooks_WebAddress}}/books/d89f6cd7-3d3d-4d3d-8d3d-3d3d3d3d3d3d
Accept: application/json

###

POST {{RiverBooks_WebAddress}}/books/{{BookID}}/pricehistory
Accept: application/json
Content-Type: application/json
{
  "id": "{{BookID}}",
  "price": 15.90
}

### Users
POST {{RiverBooks_WebAddress}}/users/
Accept: application/json
Content-Type: application/json
{
  "email": "kazeem@test.com",
  "password": "Passw0rd!"
}

###
POST {{RiverBooks_WebAddress}}/users/login
Accept: application/json
Content-Type: application/json
{
  "email": "kazeem@test.com",
  "password": "Passw0rd!"
}

###
@token=
###
# Add item to cart
POST {{RiverBooks_WebAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "bookId": "{{BookID}}",
  "quantity": 1
}

###

#List items in cart
GET {{RiverBooks_WebAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###
# List all orders
GET {{RiverBooks_WebAddress}}/orders
Accept: application/json
Authorization: Bearer {{token}}

###
# Checkout Cart
POST {{RiverBooks_WebAddress}}/cart/checkout
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "shippingAddressId": "d89f6cd7-3d3d-4d3d-8d3d-3d3d3d3d3d3d",
  "billingAddressId": "d89f6cd7-3d3d-4d3d-8d3d-3d3d3d3d3d3d"
}