@RiverBooks_WebAddress = https://localhost:7086

GET {{RiverBooks_WebAddress}}/books/
Accept: application/json

###

@BookID=b89f6cd7-3d3d-4d3d-8d3d-3d3d3d3d3d3d
GET {{RiverBooks_WebAddress}}/books/{{BookID}}
Accept: application/json

###

POST {{RiverBooks_WebAddress}}/books/
Accept: application/json
Content-Type: application/json
{
  "id": "d89f6cd7-3d3d-4d3d-8d3d-3d3d3d3d3d3d",
  "title": "The River",
  "author": "Peter Heller",
  "price": 15.99
}

###
DELETE {{RiverBooks_WebAddress}}/books/d89f6cd7-3d3d-4d3d-8d3d-3d3d3d3d3d3d
Accept: application/json

###

POST {{RiverBooks_WebAddress}}/books/{{BookID}}/pricehistory
Accept: application/json
Content-Type: application/json
{
  "id": "{{BookID}}",
  "price": 15.90
}

### Users
POST {{RiverBooks_WebAddress}}/users/
Accept: application/json
Content-Type: application/json
{
  "email": "kazeem@test.com",
  "password": "Passw0rd!"
}

###
POST {{RiverBooks_WebAddress}}/users/login
Accept: application/json
Content-Type: application/json
{
  "email": "kazeem@test.com",
  "password": "Passw0rd!"
}

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJrYXplZW1AdGVzdC5jb20iLCJpYXQiOjE3MjAxOTk3ODksImV4cCI6MTcyMDIwMzM4OSwibmJmIjoxNzIwMTk5Nzg5fQ.z-nTO0OZJ2ZPway78fuu7pT_-uD7iNP4cf6VaeSmDQ8
###